Saudi Digital Concierge - Data Exploration

In [7]:
import pandas as pd
import numpy as np
# openpyxl is required by pandas.read_excel() for .xlsx files
try:
    import openpyxl
except ModuleNotFoundError:
    import sys
    !{sys.executable} -m pip install openpyxl
    import openpyxl

In [8]:
df = pd.read_csv("C:\\Users\\bedoor.alsulami\\AppData\\Local\\Packages\\PythonSoftwareFoundation.PythonManager_3847v3x7pw1km\\AppData\\saudi-Digital-Concierge\\data\\raw\\riyadh_places\\riyadh_places_8836x9.csv", encoding="utf-8")

df.head()

,id,place_name,is_restaurant,categories,average_rating,rate_count,granular_category,latitude,longitude
0,1,Shawarma Alaz,RESTAURANT,Sandwich|Fast Food|Shawarma,3.0,3,restaurants,24.645118,46.717640
1,2,Eben Ezar,RESTAURANT,Asian|Japanese,3.2,5,restaurants,24.646631,46.717658
2,3,Chowking,RESTAURANT,Noodles,4.5,305,restaurants,24.646194,46.717444
3,4,100 islands delights,RESTAURANT,Asian|Seafood,4.4,239,restaurants,24.646334,46.717329
4,5,CUSINA Cafe,RESTAURANT,Coffee,4.7,19,restaurants,24.645628,46.717110

In [9]:
df.shape
df.columns
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 8836 entries, 0 to 8835
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 8836 non-null   int64
 1   place_name         8836 non-null   str
 2   is_restaurant      8836 non-null   str
 3   categories         8822 non-null   str
 4   average_rating     8836 non-null   float64
 5   rate_count         8836 non-null   int64
 6   granular_category  8836 non-null   str
 7   latitude           8836 non-null   float64
 8   longitude          8836 non-null   float64
dtypes: float64(3), int64(2), str(4)
memory usage: 621.4 KB

np.int64(0)

In [12]:
df["is_restaurant"].value_counts()

is_restaurant
RESTAURANT    8703
OTHER          133
Name: count, dtype: int64

In [14]:
df["granular_category"].value_counts().head(20)

granular_category
restaurants              8487
flowers_and_plants        143
pharmacies                 65
Butchery                   18
specialty_and_ethnic       16
charity                    15
supermarket                12
darkstores                 11
Hypermarket                11
nuts_and_dried_fruits       7
Pets                        7
fruits_and_vegetables       6
beauty                      5
dairy_products              5
electronics                 5
health_and_wellness         4
home_and_gifts              4
mini_market                 3
optics                      3
bakery                      2
Name: count, dtype: int64

In [15]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df["id"].duplicated().sum())
print("Duplicate place names:", df["place_name"].duplicated().sum())

Duplicate rows: 0
Duplicate IDs: 0
Duplicate place names: 3587

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

print(
    "Duplicate reviews:",
    df["processed_reviews"].duplicated().sum()
)

Duplicate rows: 5
Duplicate reviews: 12

In [16]:
df["average_rating"].describe()

count    8836.000000
mean        3.809484
std         1.298362
min         0.000000
25%         3.800000
50%         4.200000
75%         4.500000
max         5.000000
Name: average_rating, dtype: float64

In [17]:
df["rate_count"].describe()

count     8836.000000
mean       183.598348
std        589.104117
min          0.000000
25%          8.000000
50%         39.000000
75%        158.000000
max      19808.000000
Name: rate_count, dtype: float64

In [18]:
df[df["place_name"].duplicated(keep=False)] \
    .sort_values("place_name") \
    [["id", "place_name", "average_rating", "rate_count", "latitude", "longitude"]] \
    .head(30)

,id,place_name,average_rating,rate_count,latitude,longitude
4291,4292,% Arabica,4.6,53,24.766907,46.621804
1935,1936,% Arabica,4.5,120,24.731831,46.647961
6904,6905,&nbsp;Vidro Pizza,0.0,0,24.772487,46.653858
7545,7546,&nbsp;Vidro Pizza,5.0,1,24.806922,46.757647
3656,3657,1/4 Dhabiha,5.0,1,24.804230,46.634844
1617,1618,1/4 Dhabiha,0.0,0,24.792609,46.767928
1903,1904,1/4 Dhabiha,0.0,0,24.731978,46.678260
5135,5136,1/4 kabab,2.4,7,24.808611,46.806566
3927,3928,1/4 kabab,3.9,65,24.814708,46.745119
7507,7508,12 Cups,4.3,213,24.731400,46.753905
5495,5496,12 Cups,4.4,82,24.765552,46.671201
2653,2654,12 Cups,4.4,164,24.803461,46.673788
5370,5371,180 Degree Bakery,0.0,0,24.728626,46.691608
4098,4099,180 Degree Bakery,5.0,1,24.826290,46.618919
8576,8577,3K Chocolate,5.0,1,24.707754,46.786430
7342,7343,3K Chocolate,0.0,0,24.739740,46.766850
2691,2692,3K Chocolate,0.0,0,24.827722,46.682272
8764,8765,3K Chocolate,0.0,0,24.570423,46.650052
5451,5452,3K Chocolate,0.0,0,24.766725,46.679845
8507,8508,4 Twins,4.4,767,24.535611,46.692746
1732,1733,4 Twins,4.7,87,24.757313,46.719062
5335,5336,4 Twins,4.3,270,24.745757,46.705007
8826,8827,4 Twins,4.3,371,24.726691,46.779933
2537,2538,4 Twins,4.4,576,24.804538,46.694060
7188,7189,4 Twins,4.3,391,24.780188,46.773296
5877,5878,44x coffee,4.5,312,24.697509,46.771668
3056,3057,44x coffee,4.3,135,24.831741,46.674756
7727,7728,50 Fruits,4.7,110,24.683296,46.790489
3940,3941,50 Fruits,4.6,451,24.752745,46.676329
7498,7499,5×5,0.0,0,24.801023,46.788219

In [19]:
df[df["average_rating"] == 0][
    ["place_name", "average_rating", "rate_count", "latitude", "longitude"]
].head(20)

,place_name,average_rating,rate_count,latitude,longitude
15,BANA,0.0,0,24.633701,46.716946
24,Alharfoosh,0.0,0,24.658017,46.710263
29,NG Beauty,0.0,0,24.640424,46.702796
34,Methaas Bakery &amp; Desserts,0.0,0,24.628968,46.739317
173,Nuiava,0.0,0,24.676850,46.692222
174,Mass Sweets,0.0,0,24.676850,46.692222
175,El Artisano,0.0,0,24.676850,46.692222
177,Flavonoid Sweets,0.0,0,24.676850,46.692222
178,Lagouter,0.0,0,24.676850,46.692222
179,Raqy,0.0,0,24.676850,46.692222
181,Kenaz,0.0,0,24.676850,46.692222
203,Noodle Way,0.0,0,24.663826,46.683033
231,Delight,0.0,0,24.676850,46.692222
237,TREAT,0.0,0,24.676850,46.692222
239,VONA SWEET,0.0,0,24.676850,46.692222
240,La Merna,0.0,0,24.676850,46.692222
242,Kosin,0.0,0,24.676850,46.692222
243,PECANOLLI,0.0,0,24.676850,46.692222
247,Mo Sweets,0.0,0,24.676855,46.692137
249,Arena,0.0,0,24.676908,46.692254

In [20]:
print("Rating = 0:", (df["average_rating"] == 0).sum())
print("Rate count = 0:", (df["rate_count"] == 0).sum())

Rating = 0: 749
Rate count = 0: 749